<a href="https://colab.research.google.com/github/youngdelan/NIBS/blob/master/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
cars=pd.read_excel("/Cars.xlsx")
cars.head() #displaying the first 5 rows

   Dodge  2018
0    Rs8  2020
1     M4  2013
2    CLS  2030
3    G63  1994
4  M14oi  1990

In [ ]:
import pandas as pd
cars=pd.read_excel("/Cars.xlsx")
cars.dtypes #display the datatypes

Dodge    object
2018      int64
dtype: object

In [ ]:
import pandas as pd
cars=pd.read_excel("/Cars.xlsx")
cars.describe() #gives summary statistics

              2018
count     9.000000
mean   2011.888889
std      12.484435
min    1990.000000
25%    2012.000000
50%    2015.000000
75%    2017.000000
max    2030.000000

In [ ]:
dodge=cars["Dodge"]#selecting a specific collumn
print(dodge)

0          Rs8
1           M4
2          CLS
3          G63
4        M14oi
5        Supra
6      Mustang
7    Maserrati
8      Buggati
Name: Dodge, dtype: object

In [ ]:
dodge=cars[['Dodge','2018']]#selecting two columns
dodge.head()

KeyError: "['2018'] not in index"